# -----------------------------------------
# Base image
# -----------------------------------------
FROM python:3.11-slim AS base

# Install system deps (Postgres client + build tools)
RUN apt-get update && apt-get install -y curl --no-install-recommends \
        build-essential \
        libpq-dev \
        && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd --create-home appuser
WORKDIR /app

# -----------------------------------------
# Install Python packages
# -----------------------------------------
COPY services/users/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# -----------------------------------------
# Copy application
# -----------------------------------------
COPY services/users/app ./app

# Copy only the env file explicitly
# COPY .env .env

# Switch to non-root user
USER appuser

# -----------------------------------------
# Expose and run server
# -----------------------------------------
EXPOSE 8001

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
