# -----------------------------------------
# Base image
# -----------------------------------------
FROM node:20-alpine AS base

WORKDIR /app

# Create user (non-root for security)
RUN addgroup -S app && adduser -S app -G app

# -----------------------------------------
# Install deps first (cache layer)
# -----------------------------------------
COPY services/cart/package*.json ./
RUN npm install

# -----------------------------------------
# Copy application
# -----------------------------------------
COPY services/cart ./

# Install curl for healthcheck
RUN apk add --no-cache curl

# Switch to non-root user
USER app

# -----------------------------------------
# Expose + start server
# -----------------------------------------
EXPOSE 8003

CMD ["npm", "start"]
